### ISSUE TITLE
feature request: automatic disablePotentiostat() after some maximum time

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/Thales-Remote-Python#10]
There is a feature for the PP2x2 series to set a maximum time after which the device shall turn off any voltage applied. This would be really useful for the Zennium devices as well.

Or is there already such a feature?

**Comment by maxkrapp1** [comment]
With the DCSequencer you can output arbitrary voltage and current waveforms like ramps or constant current or constant voltage. The sequence is specified in [text form](https://doc.zahner.de/manuals/sequencer.pdf).

Here you can simply define a dc sequence that holds constant current for e.g. 10 minutes and then switches off the potentiostat.

The following example uses the sequencer:
https://github.com/Zahner-elektrik/Thales-Remote-Python/blob/main/Examples/DCSequencer/DCSequencer.ipynb

I am closing the ticket because the feature already exists.
