### ISSUE TITLE
script_wrapper and error of thales version

### ISSUE THREAD

**Issue by fmondi** [Zahner-elektrik/Thales-Remote-Python#21]
I downloaded the latest thales version from the Zahner website (Thales XT5.8.7) but the minimum version in script_wrapper.py is 5.9.0, so whenever i try to connect to thales remote the script stops because an error is raised. Is it a bug or there's a newer version of Thales?

**Comment by Plankokan** [comment]
Hi,
dont know if its the official way, but this works: https://software.zahner.de/thalesxt/ThalesXT5.9.0_Setup.exe

**Comment by maxkrapp1** [comment]
The version 5.9.0 unfortunately contains a bug with power potentiostats in the DCSequencer, so it was not distributed.

The best way is to install an old version of the package, because it has new features, which are not included in 5.8.7.

```
pip install thales-remote==1.2.0
```

If you don't use power potentiostats with the DC Sequencer, you can install 5.9.0. Otherwise you have to switch back to 5.8.7.

**Comment by fmondi** [comment]
Ok, the version of thales-remote i have installed is 1.2.0 though. I just downloaded it from pypi to double check and i can see that in script_wrapper.py the value for minimum version of thales is 5.9.0. 
Can i change that value to 5.8.7?

**Comment by maxkrapp1** [comment]
Sorry 1.1.2 is the correct version. The 1.2.0 and 1.2.1 contain new features and fixes for the 5.9.1.

```
pip install thales-remote==1.1.2
```

**Comment by maxkrapp1** [comment]
It also works to simply enter a lower software version in the source file. Only new features of the package do not work then.

**Comment by fmondi** [comment]
Ok, thanks. I think i will try with 1.2.0 and modifying the software version in the source file, at the moment we only need basic functions.

**Comment by maxkrapp1** [comment]
Okay, then the package version is not relevant. Then you could also use version 1.2.1.

I have marked the 1.2.0 and 1.2.1 packages as pre-release on GitHub. But I cannot remove them from pypi because ZENNIUM XC customers get version 5.9.0.

I will close the ticket when the Python version matches the current released Thales version, in case others notice the problem.

**Comment by maxkrapp1** [comment]
Now the Python package can be updated and the Thales version 5.9.1 can be installed.

https://software.zahner.de/thalesxt/ThalesXT5.9.1_Setup.exe
