### ISSUE TITLE
Check that measurement is running

### ISSUE THREAD

**Issue by fmondi** [Zahner-elektrik/Thales-Remote-Python#22]
Hi, is there a command that can be sent to check if a measurement is running, such as an EIS? I tried checking in the script-wrapper and in the remote-2 manual but i could not find something that seems to work.

**Comment by maxkrapp1** [comment]
No, the controlling instance, i.e. the python script, knows whether a measurement has been started. The functions are always called blocking. So only when the measurement is finished the function will return.

Since you always have to be connected to the device during the measurement, there should never be this problem that you do not know whether a measurement is running.

**Comment by fmondi** [comment]
Ok, thanks for the clarification. In case of connection breaking during the measurement, or having to restart the python script, what would happen? Would the system finish the measurement anyway? And after restarting the script, would it respond to a following EIS command by restarting the EIS acquisition or queue a new one after the running one?

**Comment by maxkrapp1** [comment]
It is best to completely restart the Term software and the measurement device if the connection breaks down.

For example, after the EIS measurement, the data is saved, then the remote script Python tries to respond and this fails when the client is disconnected. However, reconnecting works in most cases.
