### ISSUE TITLE
support Python 3.7 and 3.8

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/Thales-Remote-Python#25]
My colleague gets the error: `TypeError: 'type' object is not subscriptable` when importing from this library.

[StackOverflow says](https://stackoverflow.com/questions/63460126/typeerror-type-object-is-not-subscriptable-in-a-function-signature) that for Python versions prior to 3.9, you need to `from __future__ import annotations`. I guess that the `import` statement should be added to each module header. In

**Comment by maxkrapp1** [comment]
We have specified in pyproject.toml that at least python 3.9 is required. We test the released versions with the latest python and 3.9.17.
Everything before Python 3.9 is no longer officially supported by us because of the missing types and annotations. Which are an extremely helpful and useful feature in our opinion.

If the library is to be used with a version not released by us, this is done at your own risk with the necessary patches, as we do not test with this version to ensure functionality.
"The future statement is intended to ease migration to future versions of Python that introduce incompatible changes to the language. It allows use of the new features on a per-module basis before the release in which the feature becomes standard."
https://docs.python.org/3/reference/simple_stmts.html#future-statements

We recommend using a newer Python version if possible. Since the official support of Python 3.7 has expired and Python 3.8 support ends in October.
